#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP
#define DEFAULT_WINDOW_WIDTH 1200
#define DEFAULT_WINDOW_HEIGHT 900
#define WINDOW_TITLE "supra's snake game"
#define FPS 60

#define BORDER_POS (Vector2){200.0, 50.0}
#define BORDER_THICKNESS 1
#define BORDER_WIDTH 800.0f
#define BORDER_HEIGHT 800.0f

#define MAP_CELL_SIZE 40.0f
#define MAP_ROWS BORDER_WIDTH / MAP_CELL_SIZE
#define MAP_COLS BORDER_HEIGHT / MAP_CELL_SIZE
#define INNER_CELL_SIZE 32.0f

#define BORDER_OFFSET 4.0f

#define CELL_CORNER_LINE_LENGTH 6.0f

#define DYNAMIC_OFFSET (Vector2){center.x - DEFAULT_WINDOW_WIDTH / 2.0f, center.y - DEFAULT_WINDOW_HEIGHT / 2.0f}

#define SNAKE_SEGMENT_SIZE 20.0f

#define SNAKE_STARTING_POSITION (Vector2){BORDER_POS.x + 360, BORDER_POS.y + 360}

#define MOVE_INTERNAL 0.15f
#endif
